import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

import type { Channel, Run } from '../state/AppState';
import { formatNumber, getLanguage, t } from '../i18n/i18n';
import { chartToDataUrl } from './png';
import { timestampedFilename, triggerDownload } from './csv';

const FONT_URL_BASE = `${import.meta.env.BASE_URL}fonts/Roboto-Regular.ttf`;
const FONT_NAME = 'Roboto';

let cachedFontBase64: string | null = null;

async function loadRobotoBase64(): Promise<string> {
  if (cachedFontBase64) return cachedFontBase64;
  const res = await fetch(FONT_URL_BASE);
  if (!res.ok) throw new Error(`Failed to load Roboto font from ${FONT_URL_BASE}`);
  const buf = new Uint8Array(await res.arrayBuffer());
  // Convert to base64. For browsers this is fastest via btoa + binary string.
  let bin = '';
  for (let i = 0; i < buf.length; i++) bin += String.fromCharCode(buf[i]!);
  cachedFontBase64 = btoa(bin);
  return cachedFontBase64;
}

export type PdfMetadata = {
  className: string;
  students: string[];
  experimentTitle: string;
  notes: string;
};

export type PdfOptions = {
  runs: readonly Run[];
  channels: readonly Channel[];
  metadata: PdfMetadata;
  chartCanvas: HTMLCanvasElement | null;
};

/**
 * Build and download a single-page PDF protocol matching spec §13.2.
 *
 * Layout (A4 portrait, 210×297 mm):
 *   [Header band: title + tagline]
 *   [Metadata block: date, class, students, experiment title]
 *   [Chart image — full width, ~80 mm tall]
 *   [Stats table per (run × channel)]
 *   [Annotations table]
 *   [Notes block]
 *   [Footer: generated by FyzBit]
 */
export async function exportPdf(opts: PdfOptions): Promise<void> {
  const fontB64 = await loadRobotoBase64();
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  doc.addFileToVFS('Roboto-Regular.ttf', fontB64);
  doc.addFont('Roboto-Regular.ttf', FONT_NAME, 'normal');
  doc.setFont(FONT_NAME, 'normal');

  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 14;
  const accent: [number, number, number] = [27, 94, 32]; // FyzBit green
  let y = margin;

  // ── Header ───────────────────────────────────────────────
  doc.setFillColor(...accent);
  doc.rect(0, 0, pageW, 18, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.text(`FyzBit — ${t('pdf.title')}`, margin, 12);
  y = 24;

  // ── Metadata block ───────────────────────────────────────
  doc.setTextColor(20, 20, 20);
  doc.setFontSize(11);
  const dateStr = new Intl.DateTimeFormat(getLanguage() === 'cs' ? 'cs-CZ' : 'en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  }).format(new Date());

  const meta = opts.metadata;
  const metaRows: Array<[string, string]> = [
    [t('pdf.date') + ':', dateStr],
  ];
  if (meta.className) metaRows.push([t('pdf.className') + ':', meta.className]);
  if (meta.students.length > 0)
    metaRows.push([t('pdf.students') + ':', meta.students.join(', ')]);
  if (meta.experimentTitle)
    metaRows.push([t('pdf.experimentTitle') + ':', meta.experimentTitle]);

  // Use a wider gap (40 mm) so the longest label ("Název experimentu:") doesn't
  // run into the value text.
  const labelGap = 42;
  for (const [label, value] of metaRows) {
    doc.setFontSize(10);
    doc.setTextColor(110, 110, 110);
    doc.text(label, margin, y);
    doc.setTextColor(20, 20, 20);
    doc.setFontSize(11);
    doc.text(value, margin + labelGap, y);
    y += 6;
  }

  y += 2;
  doc.setDrawColor(220, 220, 220);
  doc.line(margin, y, pageW - margin, y);
  y += 4;

  // ── Chart image ──────────────────────────────────────────
  if (opts.chartCanvas) {
    const dataUrl = chartToDataUrl(opts.chartCanvas);
    if (dataUrl) {
      const imgW = pageW - 2 * margin;
      const ratio = opts.chartCanvas.height / opts.chartCanvas.width;
      const imgH = Math.min(imgW * ratio, 90);
      // imgH could be up to 90 mm.
      doc.addImage(dataUrl, 'PNG', margin, y, imgW, imgH);
      y += imgH + 4;
    }
  }

  // ── Stats table ─────────────────────────────────────────
  const visibleRuns = opts.runs.filter((r) => r.visible);
  if (visibleRuns.length > 0 && opts.channels.length > 0) {
    doc.setFontSize(12);
    doc.setTextColor(20, 20, 20);
    doc.text(t('stats.min') + ' / ' + t('stats.max') + ' / ' + t('stats.avg'), margin, y);
    y += 2;
    const head = [
      [
        t('panel.runs'),
        '',
        t('stats.min'),
        t('stats.max'),
        t('stats.avg'),
        t('stats.median'),
        t('stats.deltaY'),
      ],
    ];
    const body: string[][] = [];
    for (const r of visibleRuns) {
      for (const ch of opts.channels) {
        const stats = quickStats(r, ch.id);
        if (!stats) continue;
        body.push([
          r.name,
          `${t(ch.nameKey)} (${ch.unit})`,
          formatNumber(stats.min, 2),
          formatNumber(stats.max, 2),
          formatNumber(stats.avg, 2),
          formatNumber(stats.median, 2),
          formatNumber(stats.deltaY, 2),
        ]);
      }
    }
    doc.setFont(FONT_NAME, 'normal');
    autoTable(doc, {
      head,
      body,
      startY: y + 2,
      styles: { font: FONT_NAME, fontStyle: 'normal', fontSize: 9 },
      headStyles: {
        font: FONT_NAME,
        fontStyle: 'normal',
        fillColor: accent,
        textColor: 255,
      },
      bodyStyles: { font: FONT_NAME, fontStyle: 'normal' },
      margin: { left: margin, right: margin },
    });
    // Read updated cursor (jspdf-autotable sets lastAutoTable.finalY).
    const finalY = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable
      ?.finalY;
    y = (finalY ?? y) + 6;
  }

  // ── Annotations table ────────────────────────────────────
  const allAnnotations = visibleRuns.flatMap((r) =>
    r.annotations.map((a) => [
      formatNumber(a.t, 2),
      r.name,
      a.label,
    ]),
  );
  if (allAnnotations.length > 0) {
    if (y > pageH - 60) {
      doc.addPage();
      y = margin;
    }
    doc.setFontSize(12);
    doc.text(t('annotation.defaultLabel') + 's', margin, y);
    y += 2;
    doc.setFont(FONT_NAME, 'normal');
    autoTable(doc, {
      head: [[t('chart.time'), t('panel.runs'), t('annotation.defaultLabel')]],
      body: allAnnotations,
      startY: y + 2,
      styles: { font: FONT_NAME, fontStyle: 'normal', fontSize: 9 },
      headStyles: {
        font: FONT_NAME,
        fontStyle: 'normal',
        fillColor: accent,
        textColor: 255,
      },
      bodyStyles: { font: FONT_NAME, fontStyle: 'normal' },
      margin: { left: margin, right: margin },
    });
    const finalY = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable
      ?.finalY;
    y = (finalY ?? y) + 6;
  }

  // ── Notes block ─────────────────────────────────────────
  if (meta.notes.trim()) {
    if (y > pageH - 30) {
      doc.addPage();
      y = margin;
    }
    doc.setFontSize(12);
    doc.text(t('pdf.notes') + ':', margin, y);
    y += 5;
    doc.setFontSize(10);
    const wrapped = doc.splitTextToSize(meta.notes, pageW - 2 * margin);
    doc.text(wrapped, margin, y);
    y += wrapped.length * 5 + 4;
  }

  // ── Footer ──────────────────────────────────────────────
  doc.setFontSize(9);
  doc.setTextColor(140, 140, 140);
  doc.text(t('pdf.generatedBy') + ' · fyzbit.cz', margin, pageH - 8);

  // ── Save ────────────────────────────────────────────────
  const blob = doc.output('blob');
  triggerDownload(blob, timestampedFilename('FyzBit_protokol', 'pdf'));
}

function quickStats(
  run: Run,
  channelId: string,
): { min: number; max: number; avg: number; median: number; deltaY: number } | null {
  const col = run.values[channelId];
  if (!col || col.length === 0) return null;
  const finite = col.filter((v) => Number.isFinite(v));
  if (finite.length === 0) return null;
  const min = Math.min(...finite);
  const max = Math.max(...finite);
  const avg = finite.reduce((a, b) => a + b, 0) / finite.length;
  const sorted = [...finite].sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  const median =
    sorted.length % 2 === 0 ? (sorted[mid - 1]! + sorted[mid]!) / 2 : sorted[mid]!;
  return { min, max, avg, median, deltaY: max - min };
}
