#!/usr/bin/env node
/**
 * Generates every derived brand asset from the two sources in brand/.
 *
 *   brand/icon-source.png  — the simplified mark (no sample dots, the clip
 *                            reduced to an arrowhead). Everything that has to
 *                            survive 16 px comes from here.
 *   brand/logo-source.png  — the full logo, with the sample dots and the
 *                            detailed crocodile clip. Used where there is room.
 *
 * Outputs into public/:
 *   favicon.ico            (16/32/48, PNG-in-ICO — what browsers request by
 *                           default when nothing else matches)
 *   favicon-32.png         (32×32, the modern <link rel="icon">)
 *   apple-touch-icon.png   (180×180, opaque — iOS applies its own mask)
 *   icon-192.png           (192×192, "any" purpose)
 *   icon-512.png           (512×512, "any" purpose)
 *   icon-maskable-512.png  (512×512 with safe-area padding, "maskable")
 *   mark.png               (160×160, simplified — topbar and page headers,
 *                           where the full logo's thinner strokes go soft)
 *   logo.png               (320×320, the full logo, for the guide hero)
 *   og-image.png           (1200×630 social card, drawn here rather than
 *                           derived — a square mark scaled into a wide card
 *                           reads as nothing)
 *
 * Run with: npm run icons
 */
import sharp from 'sharp';
import { existsSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const publicDir = resolve(root, 'public');
const out = (name) => resolve(publicDir, name);

const GREEN = { r: 27, g: 94, b: 32, alpha: 1 };

const ICON_SRC = resolve(root, 'brand', 'icon-source.png');
const LOGO_SRC = resolve(root, 'brand', 'logo-source.png');

for (const [path, what] of [
  [ICON_SRC, 'icon-source.png'],
  [LOGO_SRC, 'logo-source.png'],
]) {
  if (!existsSync(path)) {
    console.error(`Missing brand/${what} — see brand/README.md.`);
    process.exit(1);
  }
}

/** Square sources only; a non-square one would silently skew every output. */
async function assertSquare(path, what) {
  const { width, height } = await sharp(path).metadata();
  if (width !== height) {
    console.error(`brand/${what} is ${width}×${height}; it must be square.`);
    process.exit(1);
  }
  if (width < 512) {
    console.warn(`brand/${what} is only ${width}px — 1024px or more is better.`);
  }
}
await assertSquare(ICON_SRC, 'icon-source.png');
await assertSquare(LOGO_SRC, 'logo-source.png');

/**
 * The mark uses exactly three colours. Anything generated by an image model —
 * and especially anything that has been through JPEG on the way here — drifts
 * off them by a few units and speckles the flat areas. Snap every pixel that
 * is *close* to a brand colour onto it exactly, and leave the rest alone:
 * those few tenths of a percent are the genuine anti-aliased edges, and
 * hard-snapping them would leave the outlines jagged.
 *
 * Idempotent — a source that is already clean passes through unchanged.
 */
const PALETTE = [
  [27, 94, 32], // #1B5E20 badge
  [255, 255, 255], // #FFFFFF axis, data line, clip
  [200, 230, 201], // #C8E6C9 sample dots
];
const SNAP_DISTANCE = 40;

async function loadCorrected(path) {
  const { data, info } = await sharp(path)
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });
  const ch = info.channels;
  let snapped = 0;
  for (let i = 0; i < info.width * info.height; i++) {
    const o = i * ch;
    const r = data[o];
    const g = data[o + 1];
    const b = data[o + 2];
    let best = null;
    let bestDist = Infinity;
    for (const c of PALETTE) {
      const d = (r - c[0]) ** 2 + (g - c[1]) ** 2 + (b - c[2]) ** 2;
      if (d < bestDist) {
        bestDist = d;
        best = c;
      }
    }
    if (bestDist <= SNAP_DISTANCE * SNAP_DISTANCE) {
      data[o] = best[0];
      data[o + 1] = best[1];
      data[o + 2] = best[2];
      snapped++;
    }
  }
  const pct = ((100 * snapped) / (info.width * info.height)).toFixed(1);
  console.info(`  ${path.split(/[\/]/).pop()}: ${pct}% of pixels snapped to the brand palette`);
  return { data, raw: { width: info.width, height: info.height, channels: ch } };
}

const iconSource = await loadCorrected(ICON_SRC);
const logoSource = await loadCorrected(LOGO_SRC);

/** A fresh sharp pipeline over the corrected pixels — instances are single-use. */
const from = (src) => sharp(src.data, { raw: src.raw });
const icon = (size) => from(iconSource).resize(size, size, { fit: 'cover' });

// ── PWA icons ────────────────────────────────────────────────────────────
await icon(192).png().toFile(out('icon-192.png'));
await icon(512).png().toFile(out('icon-512.png'));

// Maskable variant: inset the mark so the circle/squircle mask Android
// applies cannot crop it, and fill the freed border with the brand green.
const MASKABLE = 512;
const INNER = Math.round(MASKABLE * 0.78);
const inner = await icon(INNER).png().toBuffer();
await sharp({
  create: { width: MASKABLE, height: MASKABLE, channels: 4, background: GREEN },
})
  .composite([{ input: inner, gravity: 'center' }])
  .png()
  .toFile(out('icon-maskable-512.png'));

// ── Favicons ─────────────────────────────────────────────────────────────
await icon(32).png().toFile(out('favicon-32.png'));

// iOS never honours transparency here — it composites onto white, which would
// halo the rounded corners. Flatten onto the brand green.
await icon(180).flatten({ background: GREEN }).png().toFile(out('apple-touch-icon.png'));

/**
 * Minimal ICO writer. The format is a 6-byte header, one 16-byte directory
 * entry per image, then the payloads — and every browser that still asks for
 * /favicon.ico accepts PNG payloads, so no BMP encoding is needed.
 */
async function writeIco(sizes, file) {
  const images = await Promise.all(sizes.map((s) => icon(s).png().toBuffer()));
  const header = Buffer.alloc(6);
  header.writeUInt16LE(0, 0); // reserved
  header.writeUInt16LE(1, 2); // type: icon
  header.writeUInt16LE(sizes.length, 4);

  let offset = 6 + 16 * sizes.length;
  const entries = images.map((img, i) => {
    const e = Buffer.alloc(16);
    // 0 means 256 in this field; none of our sizes reach it, but be correct.
    e.writeUInt8(sizes[i] >= 256 ? 0 : sizes[i], 0);
    e.writeUInt8(sizes[i] >= 256 ? 0 : sizes[i], 1);
    e.writeUInt8(0, 2); // palette colors
    e.writeUInt8(0, 3); // reserved
    e.writeUInt16LE(1, 4); // color planes
    e.writeUInt16LE(32, 6); // bits per pixel
    e.writeUInt32LE(img.length, 8);
    e.writeUInt32LE(offset, 12);
    offset += img.length;
    return e;
  });
  writeFileSync(file, Buffer.concat([header, ...entries, ...images]));
}
await writeIco([16, 32, 48], out('favicon.ico'));

// ── Marks used in the interface ──────────────────────────────────────────
// Side by side at 28 and 40 px the simplified mark is visibly crisper than
// the full logo — thicker strokes, no sample dots muddying the line — so it
// is the one that goes in the topbar and the page headers. 160 px covers the
// 40 px slot at 4× device pixel ratio and still weighs almost nothing.
await icon(160).png().toFile(out('mark.png'));

// The full logo earns its detail only when it is large: the guide's hero.
await from(logoSource).resize(320, 320, { fit: 'cover' }).png().toFile(out('logo.png'));

// ── Open Graph card ──────────────────────────────────────────────────────
// Drawn as its own SVG rather than by scaling the mark: a 1200×630 card is
// read at thumbnail size in a chat window, so it needs the name and the
// one-line pitch, not a blown-up badge.
const OG_W = 1200;
const OG_H = 630;
const ogSvg = Buffer.from(`
<svg xmlns="http://www.w3.org/2000/svg" width="${OG_W}" height="${OG_H}" viewBox="0 0 ${OG_W} ${OG_H}">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#1B5E20"/>
      <stop offset="100%" stop-color="#0F3812"/>
    </linearGradient>
  </defs>
  <rect width="${OG_W}" height="${OG_H}" fill="url(#bg)"/>
  <g fill="none" stroke="#66BB6A" stroke-width="6" stroke-linecap="round" opacity="0.55">
    <path d="M90 470 C 220 470, 260 300, 380 300 S 560 180, 700 180"/>
  </g>
  <g fill="#66BB6A" opacity="0.75">
    <circle cx="380" cy="300" r="12"/>
    <circle cx="700" cy="180" r="12"/>
    <circle cx="90" cy="470" r="12"/>
  </g>
  <text x="90" y="200" font-family="Segoe UI, Roboto, DejaVu Sans, sans-serif"
        font-size="104" font-weight="700" fill="#FFFFFF">FyzBit</text>
  <text x="92" y="268" font-family="Segoe UI, Roboto, DejaVu Sans, sans-serif"
        font-size="40" font-weight="600" fill="#C8E6C9">Fyzika na micro:bitu</text>
  <text x="92" y="556" font-family="Segoe UI, Roboto, DejaVu Sans, sans-serif"
        font-size="30" fill="#E8EFE9">Datalogger v prohlížeči · teplota, vzdálenost, síla, tlak</text>
  <text x="92" y="600" font-family="Segoe UI, Roboto, DejaVu Sans, sans-serif"
        font-size="28" fill="#A5D6A7">Bez instalace · bez programování · zdarma pro ZŠ a SŠ</text>
</svg>`);
await sharp(ogSvg).png().toFile(out('og-image.png'));

console.info('Brand assets generated into public/.');
